### ISSUE TITLE
JDK7 support

### ISSUE THREAD

**Issue by kyxap1** [kifj/wildfly-logstash#2]
Hello,

you have wrote a very useful thing, thanks! Maintaining logstash forwarder for each WF instance is a real pain on big traffic.

Can I ask for JDK7 build support?
My 8.x WF is build on 7th java and currently I have not possibility to upgrade.
Thanks!

**Comment by kifj** [comment]
No sorry, I don't have any local facility to build and test this anymore. I recommend to fork and adapt the pom file.
